using FluentAssertions;
using Moq;
using WitnessDesktop.Models;
using WitnessDesktop.Services;
using WitnessDesktop.Services.Conversation;
using WitnessDesktop.Services.Local;
using WitnessDesktop.ViewModels;
using Xunit;

namespace WitnessDesktop.Tests.ViewModels;

// ==========================================================================
// SETTINGS NAVIGATION + SESSION RESTART
// ==========================================================================

public class MainViewModel_NavigateToSettings_Tests : MainViewModelTestBase
{
    [Fact]
    public void NavigateToSettingsCommand_Exists()
    {
        var sut = CreateSut();

        // The command should exist as a public property (generated by [RelayCommand])
        sut.NavigateToSettingsCommand.Should().NotBeNull();
    }

    [Fact]
    public async Task NavigateToSettingsCommand_CanExecute()
    {
        var sut = CreateSut();

        // NavigateToSettings should always be executable (gear icon always visible)
        sut.NavigateToSettingsCommand.CanExecute(null).Should().BeTrue();
    }
}

public class MainViewModel_RestartSession_Tests : MainViewModelTestBase
{
    [Fact]
    public async Task RestartSessionAsync_WhenDisconnected_DoesNothing()
    {
        var sut = CreateSut();
        sut.ConnectionState = ConnectionState.Disconnected;

        await sut.RestartSessionAsync();

        // Should not attempt to disconnect
        MockConversation.Verify(c => c.DisconnectAsync(), Times.Never);
    }

    [Fact]
    public async Task RestartSessionAsync_WhenConnected_DisconnectsFirst()
    {
        var sut = CreateSut();
        sut.SelectedAgent = CreateTestAgent();
        sut.SelectedTarget = CreateTestTarget();

        // Simulate connected state
        MockConversation.Setup(c => c.IsConnected).Returns(true);
        MockConversation.Setup(c => c.State).Returns(ConnectionState.Connected);
        RaiseConnectionStateChanged(ConnectionState.Connected);

        await sut.RestartSessionAsync();

        // Should disconnect
        MockConversation.Verify(c => c.DisconnectAsync(), Times.Once);
    }

    [Fact]
    public async Task RestartSessionAsync_WhenConnected_ReconnectsWithSameAgentAndTarget()
    {
        var sut = CreateSut();
        var agent = CreateTestAgent();
        var target = CreateTestTarget();
        sut.SelectedAgent = agent;
        sut.SelectedTarget = target;

        // Simulate connected state
        MockConversation.Setup(c => c.IsConnected).Returns(true);
        MockConversation.Setup(c => c.State).Returns(ConnectionState.Connected);
        RaiseConnectionStateChanged(ConnectionState.Connected);

        await sut.RestartSessionAsync();

        // Should attempt to reconnect (ConnectAsync called for the restart)
        MockConversation.Verify(c => c.ConnectAsync(It.IsAny<Agent>()), Times.Once);
    }

    [Fact]
    public async Task RestartSessionAsync_WhenConnected_PreservesAgent()
    {
        var sut = CreateSut();
        var agent = CreateTestAgent();
        var target = CreateTestTarget();
        sut.SelectedAgent = agent;
        sut.SelectedTarget = target;

        // Simulate connected state
        MockConversation.Setup(c => c.IsConnected).Returns(true);
        MockConversation.Setup(c => c.State).Returns(ConnectionState.Connected);
        RaiseConnectionStateChanged(ConnectionState.Connected);

        await sut.RestartSessionAsync();

        // Agent should still be the same after restart
        sut.SelectedAgent.Should().Be(agent);
    }

    [Fact]
    public async Task RestartSessionAsync_WhenStructuralRebootstrapRequired_DoesNotDisconnectOrReconnect()
    {
        var sut = CreateSut();
        sut.SelectedAgent = CreateTestAgent();
        sut.SelectedTarget = CreateTestTarget();

        MockStructuralSettingsTracker.Setup(s => s.RequiresRebootstrap).Returns(true);
        MockStructuralSettingsTracker.Setup(s => s.PendingSettings).Returns([nameof(ISettingsService.InferenceMode)]);

        MockConversation.Setup(c => c.IsConnected).Returns(true);
        MockConversation.Setup(c => c.State).Returns(ConnectionState.Connected);
        RaiseConnectionStateChanged(ConnectionState.Connected);

        await sut.RestartSessionAsync();

        MockConversation.Verify(c => c.DisconnectAsync(), Times.Never);
        MockConversation.Verify(c => c.ConnectAsync(It.IsAny<Agent>()), Times.Never);
    }

    [Fact]
    public void StructuralSettingsStateChanged_UpdatesRebootstrapProperties()
    {
        var sut = CreateSut();
        var changedProperties = new List<string>();
        sut.PropertyChanged += (_, e) => changedProperties.Add(e.PropertyName!);

        MockStructuralSettingsTracker.Setup(s => s.RequiresRebootstrap).Returns(true);
        MockStructuralSettingsTracker.Raise(s => s.StateChanged += null, EventArgs.Empty);

        sut.RequiresAppRebootstrap.Should().BeTrue();
        sut.CanRestartSessionShallow.Should().BeFalse();
        changedProperties.Should().Contain(nameof(MainViewModel.RequiresAppRebootstrap));
        changedProperties.Should().Contain(nameof(MainViewModel.CanRestartSessionShallow));
    }
}

// ==========================================================================
// LOCAL BRAIN PROVIDER COMPATIBILITY
// ==========================================================================

public class MainViewModel_LocalBrain_Tests : MainViewModelTestBase
{
    [Fact]
    public void MainViewModel_IsLive_RemainsTrue_WhenUsingLocalBrain()
    {
        // Local MiniCPM is a real provider, not mock — IsLive should be true
        MockBrain.Setup(b => b.ProviderName).Returns("Local MiniCPM");

        var sut = CreateSut();

        sut.IsLive.Should().BeTrue("Local MiniCPM is a real brain provider, not mock");
    }

    [Fact]
    public void MainViewModel_IsLive_ReturnsFalse_WhenUsingMockBrain()
    {
        // Mock Brain = not live (existing behavior preserved)
        MockBrain.Setup(b => b.ProviderName).Returns("Mock Brain");

        var sut = CreateSut();

        sut.IsLive.Should().BeFalse();
    }

    [Fact]
    public void MainViewModel_BrainProviderName_ReflectsLocalBrainProvider()
    {
        MockBrain.Setup(b => b.ProviderName).Returns("Local MiniCPM");

        var sut = CreateSut();

        sut.BrainProviderName.Should().Be("Local MiniCPM");
    }

    [Fact]
    public void MainViewModel_BrainProviderName_ReflectsCloudBrainProvider()
    {
        MockBrain.Setup(b => b.ProviderName).Returns("OpenRouter (google/gemini-2.5-flash)");

        var sut = CreateSut();

        sut.BrainProviderName.Should().Be("OpenRouter (google/gemini-2.5-flash)");
    }
}

// ==========================================================================
// SETTINGS VIEWMODEL — INFERENCE MODE
// ==========================================================================

public class SettingsViewModel_InferenceMode_Tests
{
    private static SettingsViewModel CreateSut(
        ISettingsService? settings = null,
        ILocalModelRuntime? runtime = null)
    {
        return new SettingsViewModel(
            settings ?? new SettingsService(),
            runtime ?? new MockLocalModelRuntime(),
            new Mock<IBargeInPolicyService>().Object);
    }

    [Fact]
    public void InferenceMode_DefaultsToCloudOnly()
    {
        var sut = CreateSut();

        sut.InferenceMode.Should().Be(InferenceMode.CloudOnly);
        sut.IsCloudOnlySelected.Should().BeTrue();
        sut.IsLocalOnlySelected.Should().BeFalse();
        sut.IsLocalFirstSelected.Should().BeFalse();
    }

    [Fact]
    public void InferenceMode_SetToLocalOnly_UpdatesComputedProperties()
    {
        var sut = CreateSut();
        var changedProps = new List<string>();
        sut.PropertyChanged += (_, e) => changedProps.Add(e.PropertyName!);

        sut.InferenceMode = InferenceMode.LocalOnly;

        sut.IsCloudOnlySelected.Should().BeFalse();
        sut.IsLocalOnlySelected.Should().BeTrue();
        sut.IsLocalFirstSelected.Should().BeFalse();
        changedProps.Should().Contain(nameof(SettingsViewModel.InferenceMode));
        changedProps.Should().Contain(nameof(SettingsViewModel.IsLocalOnlySelected));
    }

    [Fact]
    public void InferenceMode_SetToLocalFirst_UpdatesComputedProperties()
    {
        var sut = CreateSut();

        sut.InferenceMode = InferenceMode.LocalFirst;

        sut.IsCloudOnlySelected.Should().BeFalse();
        sut.IsLocalOnlySelected.Should().BeFalse();
        sut.IsLocalFirstSelected.Should().BeTrue();
    }

    [Fact]
    public void InferenceMode_PersistsThroughSettingsService()
    {
        var settings = new SettingsService();
        var sut = CreateSut(settings: settings);

        sut.InferenceMode = InferenceMode.LocalFirst;

        // Read back from the same settings service
        settings.InferenceMode.Should().Be(InferenceMode.LocalFirst);
    }

    [Fact]
    public async Task RefreshDiagnostics_CloudOnly_ShowsCloudProvider()
    {
        var sut = CreateSut();
        sut.InferenceMode = InferenceMode.CloudOnly;

        await sut.RefreshDiagnosticsAsync();

        sut.BrainProvider.Should().Be("Cloud");
        sut.VoiceProviderDisplay.Should().Be("Cloud");
        sut.IsFallbackActive.Should().BeFalse();
    }

    [Fact]
    public async Task RefreshDiagnostics_LocalOnly_Persisted_StillShowsCloud()
    {
        // Cloud-first UX: even if LocalOnly was persisted from a previous session,
        // diagnostics always present cloud values (local modes hidden in UI)
        var sut = CreateSut(runtime: new MockLocalModelRuntime(available: false));
        sut.InferenceMode = InferenceMode.LocalOnly;

        await sut.RefreshDiagnosticsAsync();

        sut.BrainProvider.Should().Be("Cloud");
        sut.VoiceProviderDisplay.Should().Be("Cloud");
        sut.IsFallbackActive.Should().BeFalse();
    }

    [Fact]
    public async Task RefreshDiagnostics_LocalFirst_Persisted_StillShowsCloud()
    {
        // Cloud-first UX: even if LocalFirst was persisted, diagnostics show cloud
        var sut = CreateSut(runtime: new MockLocalModelRuntime(available: false));
        sut.InferenceMode = InferenceMode.LocalFirst;

        await sut.RefreshDiagnosticsAsync();

        sut.BrainProvider.Should().Be("Cloud");
        sut.VoiceProviderDisplay.Should().Be("Cloud");
        sut.IsFallbackActive.Should().BeFalse();
        sut.FallbackReason.Should().BeEmpty();
    }

    [Fact]
    public async Task RefreshDiagnostics_LocalFirst_WithHealthyRuntime_StillShowsCloud()
    {
        // Cloud-first UX: local modes not active, always show cloud
        var sut = CreateSut(runtime: new MockLocalModelRuntime(available: true, brain: true, voice: true));
        sut.InferenceMode = InferenceMode.LocalFirst;

        await sut.RefreshDiagnosticsAsync();

        sut.BrainProvider.Should().Be("Cloud");
        sut.VoiceProviderDisplay.Should().Be("Cloud");
        sut.IsFallbackActive.Should().BeFalse();
        sut.FallbackReason.Should().BeEmpty();
    }

    [Fact]
    public void VoiceProvider_ChangeDoesNotAffectInferenceMode()
    {
        var sut = CreateSut();
        sut.InferenceMode = InferenceMode.LocalFirst;

        sut.VoiceProvider = "openai";

        sut.InferenceMode.Should().Be(InferenceMode.LocalFirst, "voice provider is orthogonal to inference mode");
    }
}
