using FluentAssertions;
using Moq;
using GaimerDesktop.Models;
using GaimerDesktop.Services;
using GaimerDesktop.Services.Conversation;
using GaimerDesktop.ViewModels;
using Xunit;

namespace GaimerDesktop.Tests.ViewModels;

// ==========================================================================
// SETTINGS NAVIGATION + SESSION RESTART
// ==========================================================================

public class MainViewModel_NavigateToSettings_Tests : MainViewModelTestBase
{
    [Fact]
    public void NavigateToSettingsCommand_Exists()
    {
        var sut = CreateSut();

        // The command should exist as a public property (generated by [RelayCommand])
        sut.NavigateToSettingsCommand.Should().NotBeNull();
    }

    [Fact]
    public async Task NavigateToSettingsCommand_CanExecute()
    {
        var sut = CreateSut();

        // NavigateToSettings should always be executable (gear icon always visible)
        sut.NavigateToSettingsCommand.CanExecute(null).Should().BeTrue();
    }
}

public class MainViewModel_RestartSession_Tests : MainViewModelTestBase
{
    [Fact]
    public async Task RestartSessionAsync_WhenDisconnected_DoesNothing()
    {
        var sut = CreateSut();
        sut.ConnectionState = ConnectionState.Disconnected;

        await sut.RestartSessionAsync();

        // Should not attempt to disconnect
        MockConversation.Verify(c => c.DisconnectAsync(), Times.Never);
    }

    [Fact]
    public async Task RestartSessionAsync_WhenConnected_DisconnectsFirst()
    {
        var sut = CreateSut();
        sut.SelectedAgent = CreateTestAgent();
        sut.SelectedTarget = CreateTestTarget();

        // Simulate connected state
        MockConversation.Setup(c => c.IsConnected).Returns(true);
        MockConversation.Setup(c => c.State).Returns(ConnectionState.Connected);
        RaiseConnectionStateChanged(ConnectionState.Connected);

        await sut.RestartSessionAsync();

        // Should disconnect
        MockConversation.Verify(c => c.DisconnectAsync(), Times.Once);
    }

    [Fact]
    public async Task RestartSessionAsync_WhenConnected_ReconnectsWithSameAgentAndTarget()
    {
        var sut = CreateSut();
        var agent = CreateTestAgent();
        var target = CreateTestTarget();
        sut.SelectedAgent = agent;
        sut.SelectedTarget = target;

        // Simulate connected state
        MockConversation.Setup(c => c.IsConnected).Returns(true);
        MockConversation.Setup(c => c.State).Returns(ConnectionState.Connected);
        RaiseConnectionStateChanged(ConnectionState.Connected);

        await sut.RestartSessionAsync();

        // Should attempt to reconnect (ConnectAsync called for the restart)
        MockConversation.Verify(c => c.ConnectAsync(It.IsAny<Agent>()), Times.Once);
    }

    [Fact]
    public async Task RestartSessionAsync_WhenConnected_PreservesAgent()
    {
        var sut = CreateSut();
        var agent = CreateTestAgent();
        var target = CreateTestTarget();
        sut.SelectedAgent = agent;
        sut.SelectedTarget = target;

        // Simulate connected state
        MockConversation.Setup(c => c.IsConnected).Returns(true);
        MockConversation.Setup(c => c.State).Returns(ConnectionState.Connected);
        RaiseConnectionStateChanged(ConnectionState.Connected);

        await sut.RestartSessionAsync();

        // Agent should still be the same after restart
        sut.SelectedAgent.Should().Be(agent);
    }
}
